#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Deploy VideoSense to EKS.
#
#   1. reads machine-specific values from ../infra/.videosense.env
#      (generated by ../infra/aws-provision.sh)
#   2. refreshes the ECR pull secret (ECR tokens expire after 12h —
#      re-run this script to refresh)
#   3. creates the app secrets from ../.env (never committed)
#   4. substitutes placeholders and applies every k8s/*.yaml
#   5. waits for the ALB and prints its URL
#
# Usage: ./k8s/apply.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_ENV="$SCRIPT_DIR/../infra/.videosense.env"
ROOT_ENV="$SCRIPT_DIR/../.env"

if [ ! -f "$INFRA_ENV" ]; then
  echo "!! infra/.videosense.env not found — run ../infra/aws-provision.sh first."
  exit 1
fi
source "$INFRA_ENV"

CORS_ORIGIN="${CORS_ORIGIN:-https://videosense.vercel.app}"
ECR_ACCOUNT="$ACCOUNT.dkr.ecr.$REGION.amazonaws.com"

if [ ! -f "$ROOT_ENV" ]; then
  echo "!! ../.env not found — MISTRAL_API_KEY lives there."
  exit 1
fi

# ── 1. ECR pull credentials ────────────────────────────────────────────────
echo "==> Refreshing ECR pull secret (ecr-cred) ..."
ECR_PASS="$(aws ecr get-login-password --region "$REGION")"
kubectl create secret docker-registry ecr-cred \
  --docker-server="$ECR_ACCOUNT" \
  --docker-username=AWS \
  --docker-password="$ECR_PASS" \
  --dry-run=client -o yaml | kubectl apply -f -
unset ECR_PASS

# ── 2. App secrets from ../.env ────────────────────────────────────────────
mistral_key="$(grep -E '^MISTRAL_API_KEY' "$ROOT_ENV" | head -1 \
  | sed -E 's/^[^=]*=[[:space:]]*"?([^"]*)"?[[:space:]]*$/\1/')"
sarvam_key="$(grep -E '^SARVAM_API_KEY' "$ROOT_ENV" | head -1 \
  | sed -E 's/^[^=]*=[[:space:]]*"?([^"]*)"?[[:space:]]*$/\1/')"

echo "==> Creating app secret (videosense-secrets) ..."
kubectl create secret generic videosense-secrets \
  --from-literal="MISTRAL_API_KEY=$mistral_key" \
  --from-literal="SARVAM_API_KEY=$sarvam_key" \
  --dry-run=client -o yaml | kubectl apply -f -

# ── 3. Manifests with placeholder substitution ─────────────────────────────
echo "==> Applying manifests ..."
for f in "$SCRIPT_DIR"/*.yaml; do
  echo "    - $(basename "$f")"
  sed -e "s/YOUR_BUCKET/$JOBS_BUCKET/g" \
      -e "s/YOUR_EFS_FS_ID/$EFS_FS_ID/g" \
      -e "s/YOUR_EFS_AP_MODELS/$EFS_AP_MODELS/g" \
      -e "s/YOUR_EFS_AP_CHROMA/$EFS_AP_CHROMA/g" \
      -e "s/YOUR_AWS_REGION/$REGION/g" \
      -e "s/YOUR_ACCOUNT_ID/$ACCOUNT/g" \
      -e "s/YOUR_ECR_ACCOUNT/$ECR_ACCOUNT/g" \
      -e "s|YOUR_CORS_ORIGIN|$CORS_ORIGIN|g" \
      "$f" | kubectl apply -f -
done

# ── 4. Wait for the ALB ────────────────────────────────────────────────────
echo "==> Waiting for the ALB (up to 5 min) ..."
ALB_URL=""
for _ in $(seq 1 60); do
  ALB_URL="$(kubectl get ingress videosense-ingress -n default \
    -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)"
  [ -n "$ALB_URL" ] && break
  sleep 5
done

echo
echo "=============================================================="
if [ -n "$ALB_URL" ]; then
  echo " Deployed! ALB URL: http://$ALB_URL"
  echo " Smoke test:"
  echo "   python scripts/e2e_smoke.py --source <youtube-url> \\"
  echo "     --api-url http://$ALB_URL --sum-url http://$ALB_URL"
else
  echo " Ingress created but ALB not ready yet — check:"
  echo "   kubectl describe ingress videosense-ingress"
fi
echo "=============================================================="
